# Browser timeouts (seconds)
PAGE_LOAD_TIMEOUT = 10
COOKIE_MODAL_TIMEOUT = 2
RESULT_WAIT_TIMEOUT = 30
POST_CLICK_DELAY = 0.5
POST_COOKIE_DISMISS_DELAY = 0.5
PLAYWRIGHT_POST_CLICK_DELAY = 0.3

# Selenium ActionChains optimization
ACTION_CHAINS_BATCH_SIZE = 10

# Metrics collection
METRICS_POLL_INTERVAL = 0.1
BYTES_TO_MB = 1024 * 1024

# Screenshot naming
SCREENSHOT_BEFORE_SUFFIX = "_before.png"
SCREENSHOT_AFTER_SUFFIX = "_after.png"

# Browser viewport
DEFAULT_VIEWPORT_WIDTH = 1920
DEFAULT_VIEWPORT_HEIGHT = 1080

# Result extraction delay
RESULT_EXTRACTION_DELAY = 1.0
